// resources/js/Components/Chart.vue
<script setup>
import { onMounted, onUnmounted, ref, watch } from "vue";

const props = defineProps({
  options: {
    type: Object,
    default: () => ({}),
  },
  type: {
    type: String,
    default: "line",
  },
  height: {
    type: Number,
    default: 350,
  },
  series: {
    type: Array,
    default: () => [],
  },
  labels: {
    type: Array,
    default: () => [],
  },
  title: {
    type: String,
    default: "",
  },
});

const chartNode = ref(null);
let chart = null;

const getChartOptions = () => ({
  chart: {
    type: props.type,
    height: props.height,
    toolbar: {
      show: false,
    },
  },
  series: props.series,
  labels: props.labels,
  title: {
    text: props.title,
    align: "left",
  },
  ...props.options,
});

onMounted(async () => {
  const { default: ApexCharts } = await import("apexcharts");
  chart = new ApexCharts(chartNode.value, getChartOptions());
  chart.render();
});

onUnmounted(() => {
  if (chart) {
    chart.destroy();
  }
});

watch(
  () => [
    props.options,
    props.type,
    props.height,
    props.series,
    props.labels,
    props.title,
  ],
  () => {
    if (chart) {
      chart.updateOptions(getChartOptions());
    }
  },
  { deep: true },
);
</script>

<template>
  <div
    class="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700 shadow-sm"
  >
    <div ref="chartNode"></div>
  </div>
</template>

// resources/js/Components/Chart.svelte
<script>
  import { onMount, onDestroy } from "svelte";
  import ApexCharts from "apexcharts";

  export let options = {};
  export let type = "line";
  export let height = 350;
  export let series = [];
  export let labels = [];
  export let title = "";

  let chartNode;
  let chart;

  $: chartOptions = {
    chart: {
      type: type,
      height: height,
      toolbar: {
        show: false,
      },
    },
    series: series,
    labels: labels,
    title: {
      text: title,
      align: "left",
    },
    ...options,
  };

  $: if (chart && chartOptions) {
    chart.updateOptions(chartOptions);
  }

  onMount(() => {
    chart = new ApexCharts(chartNode, chartOptions);
    chart.render();
  });

  onDestroy(() => {
    if (chart) {
      chart.destroy();
    }
  });
</script>

<div
  class="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-200 dark:border-gray-700 shadow-sm"
>
  <div bind:this={chartNode}></div>
</div>
